### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by Muhammad-Shahid-Jamal** [Muhammad-Shahid-Jamal/NextPallette#2]
create a landing page in which user can see nextjs components by category and components as well

**Comment by arhamabeer** [comment]
I've developed dozens of landing pages in React and Next JS, and this one looks pretty similar to them. Please assign this issue to me I can easily developed this landing page

**Comment by Muhammad-Shahid-Jamal** [comment]
please share screen shot before creating PR

**Comment by arhamabeer** [comment]
I have attached the Screenshots of both views, i-e Desktop view and Mobile View. I am also creating PR for a successful merge.

![image](https://github.com/Muhammad-Shahid-Jamal/NextPallette/assets/57269012/5d7b042d-34da-4fb6-a1cb-a10ae614f5f1)
![image](https://github.com/Muhammad-Shahid-Jamal/NextPallette/assets/57269012/6c89a227-cff0-4980-bb64-89ce90a4cdf3)

**Comment by Muhammad-Shahid-Jamal** [comment]
looks good @arhamabeer
