### ISSUE TITLE
Show Contributors

### ISSUE THREAD

**Issue by Muhammad-Shahid-Jamal** [Muhammad-Shahid-Jamal/NextPallette#4]
### Show the contribution list in README.md file

***hint***
you can use GitHub API to show contributors.

**Comment by BkPankaj** [comment]
Hey @Muhammad-Shahid-Jamal I am interested in this project. Please assign this issue to me.

**Comment by Muhammad-Shahid-Jamal** [comment]
Sure @BkPankaj  Go Ahead

**Comment by Muhammad-Shahid-Jamal** [comment]
@BkPankaj also star the repo as well Thanks

**Comment by BkPankaj** [comment]
@Muhammad-Shahid-Jamal I have added a contributors feature, fetching the data from the GitHub API. Please verify and merge the changes.
